### ISSUE TITLE
FLTK 1.3.4 needs to be released

### ISSUE THREAD

**Issue by fltk** [fltk/test-only#1]
This is a test issue. It's true, but just for testing.

Comments may indicate things that need to be done before the relase.

**Comment by fltk** [comment]
[http://www.fltk.org/str.php?L3161](url)

Comments and README's need updates.

**Comment by fltk** [comment]
FLTK 1.3.4 has been released yesterday (Nov. 11, 2016).
http://www.fltk.org/articles.php?L1494

Note: leaving this issue open as an example only.

**Comment by Albrecht-S** [comment]
Closing this test issue now...
