### ISSUE TITLE
FLTK Migration to Git - Trying to contact former FLTK developers

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/test-only#5]
Dear former FLTK developers,

the FLTK team decided to convert our source code repository to Git and to host it either on GitHub or on GitLab. For our conversion we'd appreciate if all former contributors (with Subversion access) would send their Git user names and e-mail addresses to us to **_allow_** us to use these in our new Git repository.

For further details please read the thread ["FLTK Migration to Git - we need your assistance"](https://groups.google.com/d/msg/fltkcoredev/Wc5ciShroDc/EvGCEyjICAAJ) and take appropriate action to give us permission (send mail, reply here, whatever you choose). If you don't like your real name or mail address published in our Git repository we'll respect this - please send us a note what to use instead. Hint: for instance we can use your Subversion user name as Git user name and as "e-mail address" so you will be as "anonymous" as you were in the subversion user.

The easiest way to let us know what we shall use is the following syntax for mapping a subversion user name (SVN-User) to a Git user name (GIT-User) and mail address (mail@example.com), like this:
```
SVN-User = GIT-User <mail@example.com>
```

Thanks in advance!

Albrecht Schlosser
FLTK Team

@spitzak
@michaelrsweet
@nafeesb

**Comment by nafeesb** [comment]
Hello.  Please use nb@nafees.net as my email.

Thanks

**Comment by Albrecht-S** [comment]
I got a note that the former FLTK developer(s) 'mikko' and 'laza2000' is (are) @mikkonid. If this is true please follow the link above and contact me. Short: please tell me which username and (if you like) public email address to use for your earlier contributions. TIA

**Comment by Albrecht-S** [comment]
This repository is no longer used and will be archived and probably deleted after a while...
